Fix store_banner_dimension undefined: add default banner dimensions to dokan i18n data
- Add store_banner_dimension to dokan script localization
- Prevents Uncaught TypeError: can't access property 'width', dokan.store_banner_dimension is undefined
- The dokan.js calculateImageSelectOptions function expects store_banner_dimension object
- Added default dimensions (width: 0, height: 0, flex-width: false, flex-height: false) to avoid undefined errors on pages with banners